/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Rodo
 */
public class ViewVolumenes extends javax.swing.JPanel {

    /**
     * Creates new form ViewOpera
     */
    public ViewVolumenes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jlBaseC = new javax.swing.JLabel();
        jlAlturaC = new javax.swing.JLabel();
        jlAltura = new javax.swing.JLabel();
        jrbCubo = new javax.swing.JRadioButton();
        jrbPrisma = new javax.swing.JRadioButton();
        jrbPiramide = new javax.swing.JRadioButton();
        jtfBaseC = new javax.swing.JTextField();
        jtfAltura = new javax.swing.JTextField();
        jtfAlturaC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jbResultado = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jtfLado = new javax.swing.JTextField();
        jlLado = new javax.swing.JLabel();
        jlResultado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 153));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Volumenes");

        jlBaseC.setBackground(new java.awt.Color(255, 255, 255));
        jlBaseC.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jlBaseC.setForeground(new java.awt.Color(255, 255, 255));
        jlBaseC.setText("Base de la Cara");

        jlAlturaC.setBackground(new java.awt.Color(255, 255, 255));
        jlAlturaC.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jlAlturaC.setForeground(new java.awt.Color(255, 255, 255));
        jlAlturaC.setText("Altura de la Cara");

        jlAltura.setBackground(new java.awt.Color(255, 255, 255));
        jlAltura.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jlAltura.setForeground(new java.awt.Color(255, 255, 255));
        jlAltura.setText("Altura");

        Group.add(jrbCubo);
        jrbCubo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jrbCubo.setText("Cubo");

        Group.add(jrbPrisma);
        jrbPrisma.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jrbPrisma.setText("Prisma");

        Group.add(jrbPiramide);
        jrbPiramide.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jrbPiramide.setText("Piramide");

        jtfBaseC.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jtfAltura.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jtfAlturaC.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jtfAlturaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAlturaCActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Resultado");

        jbResultado.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jbResultado.setText("Resultado");

        jtfLado.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jlLado.setBackground(new java.awt.Color(255, 255, 255));
        jlLado.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jlLado.setForeground(new java.awt.Color(255, 255, 255));
        jlLado.setText("Lado");

        jlResultado.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlResultado.setForeground(new java.awt.Color(255, 255, 255));
        jlResultado.setText("-------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlAlturaC, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlAltura, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlBaseC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlLado, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfAlturaC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfBaseC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfLado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlResultado))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrbCubo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(60, 60, 60))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbPrisma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(15, 15, 15)
                                .addComponent(jrbPiramide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(101, 101, 101))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbCubo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbPrisma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbPiramide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jlBaseC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtfBaseC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jlAlturaC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtfAlturaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jlAltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlResultado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfAlturaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAlturaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAlturaCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup Group;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JButton jbResultado;
    public javax.swing.JLabel jlAltura;
    public javax.swing.JLabel jlAlturaC;
    public javax.swing.JLabel jlBaseC;
    public javax.swing.JLabel jlLado;
    public javax.swing.JLabel jlResultado;
    public javax.swing.JRadioButton jrbCubo;
    public javax.swing.JRadioButton jrbPiramide;
    public javax.swing.JRadioButton jrbPrisma;
    public javax.swing.JTextField jtfAltura;
    public javax.swing.JTextField jtfAlturaC;
    public javax.swing.JTextField jtfBaseC;
    public javax.swing.JTextField jtfLado;
    // End of variables declaration//GEN-END:variables
}
